### PR TITLE
Add OSGI stufss

### PR DESCRIPTION
**Pull request by cmoulliard**
- Add BundleActivator class for manager-es to deploy the micro-service (doesn't work to CDI/Weld issue), 
- Create features xml file to deploy…… apiman on Apache Karaf (= JBoss Fuse). 
- Create a shade resteasy bundle

### CODE REVIEW

**Comment by EricWittmann** [comment]
This is very cool, Charles.  I'm wondering though - what do you think about perhaps a separate apiman repository for the osgi/karaf work, rather than using apiman-servers?  I think it might be nice to really group all that stuff together.  I could create an apiman/apiman-osgi repository in github and grant you commit access to it.

Thoughts?

**Comment by cmoulliard** [comment]
I don't think that it makes sense to have another github repo as we have to manage 2 things : 
- Features XML file (= list of the bundles + config) to deploy Apiman
- Karaf Apiman cmd if we want to provide a karaf command. Could be helpful to display the services registered, organisation info, plans, ...

**Comment by EricWittmann** [comment]
Well in that case I think we may need some reorganization within this PR.  My intention for the apiman-servers repository was that each module would represent a single configuration of a micro-service.  It wasn't meant to hold command line tools and karaf features files.

So I think we either need to move those things to a separate repository _or_ move them into a sensible place within the main apiman repository.

Also I'm curious - why did you remove the shade plugin from the manager-es module?

**Comment by cmoulliard** [comment]
This is a mistake. The plugin should not be removed.

The right place of the karaf/osgi stuffs should be perhaps within the project where we package apiman distributions (eap, wildfly, ...) - https://github.com/apiman/apiman/tree/master/distro

**Comment by EricWittmann** [comment]
Agreed.  I think the right place for the karaf features.xml is in a new module `apiman/distro/karaf`.  I also think that any sort of command line tool should go into `apiman/tools`.  So perhaps we add the following new modules to the `apiman` repository:

```
distro/karaf
distro/karaf/features
distro/karaf/bundles
distro/karaf/bundles/resteasy
tools/karaf
```

That last one obviously is for the future.

What do you think?

**Comment by cmoulliard** [comment]
One remark . This project "distro/karaf/bundles/resteasy" is temporary as
normally the resteasy team should provide the project as a collection of
bundles. If this is not possible, the shade plugin can also be hosted here
: https://github.com/apache/servicemix-bundles

On Mon, Nov 30, 2015 at 6:14 PM, Eric Wittmann notifications@github.com
wrote:

> Agreed. I think the right place for the karaf features.xml is in a new
> module apiman/distro/karaf. I also think that any sort of command line
> tool should go into apiman/tools. So perhaps we add the following new
> modules to the apiman repository:
> 
> distro/karaf
> distro/karaf/features
> distro/karaf/bundles
> distro/karaf/bundles/resteasy
> tools/karaf
> 
> That last one obviously is for the future.
> 
> What do you think?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/apiman/apiman-servers/pull/2#issuecomment-160693281.

## 

Charles Moulliard
Apache Committer & PMC / Architect @RedHat
Twitter : @cmoulliard | Blog :  http://cmoulliard.github.io

**Comment by cmoulliard** [comment]
Would you like that I summit a new PR with the new maven modules discussed ?

**Comment by EricWittmann** [comment]
That would be fantastic, yes please!  :)

**Pull request closed without merging**
