### PR TITLE
Hikari && Java 8 changes

### PR DESCRIPTION
**Pull request by msavy**
As separate commits, so feel free to split. Should be okay to use Java 8 just for this project though, I reckon.

### CODE REVIEW

**Comment by EricWittmann** [comment]
Can you do me a favor - can you create two profiles for this stuff?  A java 1.7 profile and a java 1.8 profile?   Even better we could activate them based on the detected version of java?

**Comment by msavy** [comment]
>  Can you do me a favor - can you create two profiles for this stuff? A java 1.7 profile and a java 1.8 profile? Even better we could activate them based on the detected version of java?

Isn't that just the same as _not_ specifying a java version in the pom?

**Comment by EricWittmann** [comment]
I don't think so, right?  We need a different dependency if using java 1.8 vs. java 1.7.  So the only way to get things working in both environments, I _think_, is to isolate that one dependency in a profile.  No?

**Comment by msavy** [comment]
I think the _old_ dependency is only meant for 1.6 and earlier, according to their docs. Not sure why it even worked before. I’ll play around and see what combinations seem to work.

**Comment by msavy** [comment]
I've backed this out to be _just_ the Hikari version change. It seems to work properly for me with just that alteration (not java 8)

**Pull request merged**
